### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by pghmcfc** [shlomif/perl-XML-LibXSLT#5]
In the 2.001000 release a LICENSE section was added to XML::LibXSLT::Quick in which the license was stated to be MIT/expat. The rest of the dist (including the LICENSE file) says "same as perl" (i.e. GPL or Artistic). Was that intentional?

**Comment by shlomif** [comment]
Hi Paul!

On Mon, 16 May 2022 00:51:24 -0700
Paul Howarth ***@***.***> wrote:

> In the 2.001000 release a LICENSE section was added to XML::LibXSLT::Quick in
> which the license was stated to be MIT/expat. The rest of the dist (including
> the LICENSE file) says "same as perl" (i.e. GPL or Artistic). Was that
> intentional?
> 

yes, it was:
https://www.shlomifish.org/philosophy/computers/open-source/foss-licences-wars/rev2/#which-licence-same-as-perl
. IANAL/etc.

The expat licence applies to that .pm file alone.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/open-source/resources/tech-tips/

Chuck Norris used these facts to his advantage, making a huge comeback. He
didn’t get mad — he got even!
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by pghmcfc** [comment]
Thanks. I'd suggest mentioning that that one file has a different license in the LICENSE file in future releases, as I think the user expectation would be that the file covers the whole dist.

**Comment by shlomif** [comment]
done in the latest release
